version: "3"

services:
  php:
    container_name: php_test1
    build: 
      context: ./php
    ports: 
      - 8080:80
    volumes:
      - ./htdocs:/var/www/html
    restart: always
  
  db:
    container_name: mysql_test1
    image: mysql:8.0.23
    volumes:
      - mysqlvol1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
volumes:
  mysqlvol1: